# Generated by Django 4.0 on 2022-10-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(max_length=100)),
                ('product_image', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('availability', models.BooleanField()),
                ('color', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
