# Generated by Django 4.0 on 2022-10-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_product_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
