# Generated by Django 4.0 on 2022-10-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
