# Generated by Django 4.0 on 2022-10-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_cart_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='created_by',
            new_name='addcart_by',
        ),
    ]
