# Generated by Django 4.0 on 2022-10-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_order_order_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_by',
        ),
    ]
