# Generated by Django 4.0 on 2022-10-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0027_whislist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='whislist',
            new_name='wishlist',
        ),
    ]
