# Generated by Django 4.0 on 2022-10-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_rename_whislist_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='is_active',
            new_name='is_active1',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='product1',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='selling_price',
            new_name='selling_price1',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='user1',
        ),
    ]
