# Generated by Django 4.0 on 2022-10-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_rename_selling_price1_wishlist_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
