# Generated by Django 4.0 on 2022-10-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
