# Generated by Django 4.0 on 2022-10-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_wishlist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
