# Generated by Django 4.0 on 2022-10-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_wishlist_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
