# Generated by Django 4.0 on 2022-10-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_remove_wishlist_date_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
