# Generated by Django 4.0 on 2022-10-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Success', 'Success'), ('Failure', 'Failure'), ('In-progress', 'In-progress')], default='Success', max_length=200),
        ),
    ]
