# Generated by Django 4.0 on 2022-10-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_order_total_order_value_order_total_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Pending'), (0, 'FAILED')], default='Success'),
        ),
    ]
