# Generated by Django 4.0 on 2022-10-31 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0044_alter_cart_is_active_alter_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='addcart_by',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_order_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='is_active1',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
