# Generated by Django 4.0 on 2022-10-31 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_alter_cart_addcart_by_alter_cart_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_logo', models.ImageField(upload_to='image/')),
                ('year', models.IntegerField()),
                ('founder', models.CharField(max_length=200)),
                ('products', models.TextField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.brand'),
        ),
    ]
