# Generated by Django 4.0 on 2022-10-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_brand_alter_product_title_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.ManyToManyField(related_name='title', to='myapp.Brand'),
        ),
    ]
