# Generated by Django 4.0 on 2022-10-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_remove_product_title_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
