# Generated by Django 4.0 on 2022-11-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_payment_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='products',
        ),
    ]
