# Generated by Django 4.0 on 2022-11-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_remove_payment_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_order_value',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_product_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_tax',
        ),
    ]
